### ISSUE TITLE
Comparison to Tashkeela-Model for diacritics

### ISSUE THREAD

**Issue by Kentoseth** [linuxscout/mishkal#48]
Salam,

How does the diacritization of mishkal compare to: [Tashkeela-Model](https://github.com/Anwarvic/Tashkeela-Model)

That project is using training data that you made from Kaggle: [Tashkeela](https://www.kaggle.com/linuxscout/tashkeela)

Is the method you used here for diacritics more accurate than that trained model?

**Comment by Kentoseth** [comment]
I was able to find the answer here:

["Neural Arabic Text Diacritization: State of the Art Results and a Novel Approach for Machine Translation"](https://www.aclweb.org/anthology/D19-5229), Ali Fadel, Ibraheem Tuffaha, Bara' Al-Jawarneh and Mahmoud Al-Ayyoub.

**Comment by linuxscout** [comment]
Salam,
Mishkal uses Tashkeela Data set as an evaluation set only, Mishkal is rule based and not a Machine learning based. Mishkal is built on  a stuff of libraries for Arabic langauge processing, which provide more tools and resources such as:
* Stemmer: Tashaphyne
* Morphology analyzer: Qalsadi
* Tashkeela corpus
* Qutrub verb conjugatoon
* Arramooz dictionary
* etc...

Tashkeela is made by us in order to help the use of diacritized texts in machine learning training or test.

[Tashkeela: Novel corpus of Arabic vocalized texts, data for auto-diacritization systems](https://www.sciencedirect.com/science/article/pii/S2352340917300112)

We used Tashkeela to develop another product ML based named [Shakkala ](https://github.com/Barqawiz/Shakkala).
Thanks
